### ISSUE TITLE
Flow based program always rocks

### ISSUE THREAD

**Issue by chansdad** [brodavi/rhei.js#1]
I always feel and think Flow based programming is awesome . While NoFlow might have got the attention to the topic , Since long there were some frameworks which did leverage these concepts. Ex , Interworld Commerce Exchange ( non existent company ) where in the application logic is defined in pseudocode or process steps and the ui was defined in template files where each process step's output is the input to the other process step and final output for the final process step is a template or a store in db etc ..
Then there was struts flow .. 
Market sure needs a good tools that can aid in flow based programming .  Nice example and write up though.

**Comment by brodavi** [comment]
hey thanks  :)
